server.port=8080
logging.level.root=DEBUG
spring.datasource.url=jdbc:localhost:5432/devdb
spring.datasource.username=devuser
spring.datasource.password=devpass
app.http.timeout.connect=1000
app.http.timeout.read=5000
app.http.proxy.host=DEV_PROXY_HOST
app.http.proxy.port=8080
app.http.proxy.non-proxy-hosts=localhost|127.0.0.1
app.http.retry.attempts=3
app.http.retry.backoff=200
