server.port=8080
logging.level.root=INFO
spring.datasource.url=jdbc:prodserver:5432/proddb
spring.datasource.username=produser
spring.datasource.password=prodpass
app.http.timeout.connect=10000
app.http.timeout.read=30000
app.http.proxy.host=PROD_PROXY_HOST
app.http.proxy.port=8080
app.http.proxy.non-proxy-hosts=
app.http.retry.attempts=10
app.http.retry.backoff=1000
