server.port=8080
logging.level.root=DEBUG
spring.datasource.url=jdbc:localhost:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=testpass
app.http.timeout.connect=2000
app.http.timeout.read=10000
app.http.proxy.host=TEST_PROXY_HOST
app.http.proxy.port=8081
app.http.proxy.non-proxy-hosts=localhost
app.http.retry.attempts=1
app.http.retry.backoff=100
